/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify that the application is running.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description OAuth2 compatible token login, get an access token for future requests.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/universities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Universities
         * @description Get a paginated list of published universities.
         */
        get: operations["list_universities_api_v1_public_universities__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/universities/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get University Detail
         * @description Get detailed information about a specific published university.
         */
        get: operations["get_university_detail_api_v1_public_universities__university_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/universities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Universities
         * @description Get all of universities including DRAFT.
         */
        get: operations["get_universities_api_v1_admin_universities__get"];
        put?: never;
        /**
         * Create New University
         * @description Create a new university.
         */
        post: operations["create_new_university_api_v1_admin_universities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/universities/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get University
         * @description Get a university by its ID.
         */
        get: operations["get_university_api_v1_admin_universities__university_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete University
         * @description Delete a university and its programs.
         */
        delete: operations["delete_university_api_v1_admin_universities__university_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update University Partial
         * @description Update specific fields (used for the 5-step wizard).
         */
        patch: operations["update_university_partial_api_v1_admin_universities__university_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/universities/{university_id}/programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Program
         * @description Add a new program to a specific university.
         */
        post: operations["create_program_api_v1_admin_universities__university_id__programs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Program
         * @description Delete a program.
         */
        delete: operations["delete_program_api_v1_admin_programs__program_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Program
         * @description Update program details.
         */
        patch: operations["update_program_api_v1_admin_programs__program_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "USD" | "KHR";
        /**
         * DegreeLevel
         * @enum {string}
         */
        DegreeLevel: "DIPLOMA" | "ASSOCIATE" | "BACHELOR" | "MASTER" | "PHD";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProgramCreate
         * @description Schema for creating a new program.
         */
        ProgramCreate: {
            /** Name En */
            name_en: string;
            /** Name Kh */
            name_kh?: string | null;
            /** Faculty */
            faculty?: string | null;
            degree_level: components["schemas"]["DegreeLevel"];
            /** Duration Years */
            duration_years: number;
            /** Tuition Per Year */
            tuition_per_year?: number | null;
            /** Tuition Per Credit */
            tuition_per_credit?: number | null;
            /** @default USD */
            fee_currency: components["schemas"]["Currency"];
        };
        /**
         * ProgramSummary
         * @description Schema for summarizing program information.
         */
        ProgramSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name En */
            name_en: string;
            /** Name Kh */
            name_kh?: string | null;
            /** Faculty */
            faculty?: string | null;
            degree_level: components["schemas"]["DegreeLevel"];
            /** Duration Years */
            duration_years?: number | null;
            /** Tuition Fee */
            tuition_fee?: number | null;
            /** @default USD */
            fee_currency: components["schemas"]["Currency"];
        };
        /**
         * ProgramUpdate
         * @description Allows partial updates for a program via PATCH.
         */
        ProgramUpdate: {
            /** Name En */
            name_en?: string | null;
            /** Name Kh */
            name_kh?: string | null;
            /** Faculty */
            faculty?: string | null;
            degree_level?: components["schemas"]["DegreeLevel"] | null;
            /** Duration Years */
            duration_years?: number | null;
            /** Tuition Per Year */
            tuition_per_year?: number | null;
            /** Tuition Per Credit */
            tuition_per_credit?: number | null;
            fee_currency?: components["schemas"]["Currency"] | null;
            /** Overview En */
            overview_en?: string | null;
            /** Overview Kh */
            overview_kh?: string | null;
            /** Admission Req En */
            admission_req_en?: string | null;
            /** Admission Req Kh */
            admission_req_kh?: string | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "DRAFT" | "PUBLISHED";
        /**
         * UniversityCreate
         * @description Schema for creating a new university.
         */
        UniversityCreate: {
            /** Name En */
            name_en: string;
            /** Name Kh */
            name_kh?: string | null;
            /** Abbreviation */
            abbreviation?: string | null;
            type: components["schemas"]["UniversityType"];
            /** Province */
            province: string;
        };
        /**
         * UniversityDetail
         * @description Schema for detailed university information.
         */
        UniversityDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name En */
            name_en: string;
            /** Name Kh */
            name_kh?: string | null;
            /** Abbreviation */
            abbreviation?: string | null;
            type: components["schemas"]["UniversityType"];
            /** Province */
            province: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Moeys Accredited */
            moeys_accredited: boolean;
            /** Established Year */
            established_year?: number | null;
            /** Address */
            address?: string | null;
            /** Website */
            website?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Overview En */
            overview_en?: string | null;
            /** Overview Kh */
            overview_kh?: string | null;
            /** Has Scholarships */
            has_scholarships: boolean;
            /** Scholarship Info */
            scholarship_info?: string | null;
            /** Has Dormitory */
            has_dormitory: boolean;
            /** Dormitory Details */
            dormitory_details?: string | null;
            /**
             * Programs
             * @default []
             */
            programs: components["schemas"]["ProgramSummary"][];
        };
        /**
         * UniversitySummary
         * @description Schema for summarizing university information.
         */
        UniversitySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name En */
            name_en: string;
            /** Name Kh */
            name_kh?: string | null;
            /** Abbreviation */
            abbreviation?: string | null;
            type: components["schemas"]["UniversityType"];
            /** Province */
            province: string;
            /** Logo Url */
            logo_url?: string | null;
            /** Moeys Accredited */
            moeys_accredited: boolean;
            /** Established Year */
            established_year?: number | null;
        };
        /**
         * UniversityType
         * @enum {string}
         */
        UniversityType: "PUBLIC" | "PRIVATE";
        /**
         * UniversityUpdate
         * @description Schema for updating an existing university.
         */
        UniversityUpdate: {
            /** Name En */
            name_en?: string | null;
            /** Name Kh */
            name_kh?: string | null;
            /** Abbreviation */
            abbreviation?: string | null;
            type?: components["schemas"]["UniversityType"] | null;
            status?: components["schemas"]["Status"] | null;
            /** Moeys Accredited */
            moeys_accredited?: boolean | null;
            /** Province */
            province?: string | null;
            /** Address */
            address?: string | null;
            /** Website */
            website?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Overview En */
            overview_en?: string | null;
            /** Overview Kh */
            overview_kh?: string | null;
            /** Established Year */
            established_year?: number | null;
            /** Has Scholarships */
            has_scholarships?: boolean | null;
            /** Scholarship Info */
            scholarship_info?: string | null;
            /** Has Dormitory */
            has_dormitory?: boolean | null;
            /** Dormitory Details */
            dormitory_details?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_universities_api_v1_public_universities__get: {
        parameters: {
            query?: {
                /** @description Filter by province */
                province?: string | null;
                /** @description Filter by type, PUBLIC or PRIVATE */
                type?: string | null;
                /** @description Page number */
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_university_detail_api_v1_public_universities__university_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_universities_api_v1_admin_universities__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_university_api_v1_admin_universities__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniversityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_university_api_v1_admin_universities__university_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_university_api_v1_admin_universities__university_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_university_partial_api_v1_admin_universities__university_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniversityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_program_api_v1_admin_universities__university_id__programs__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_program_api_v1_admin_programs__program_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_program_api_v1_admin_programs__program_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
