import type { LucideIcon } from "lucide-react";
import {
  AlertCircle,
  Award,
  BarChart3,
  Bookmark,
  Bot,
  BookOpen,
  BrainCircuit,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  Code2,
  Cpu,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  FileText,
  Flag,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  HelpCircle,
  Hourglass,
  Info,
  Link2,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Percent,
  Phone,
  Search,
  Send,
  Server,
  Share2,
  ShieldCheck,
  Star,
  TrendingUp,
  Users,
  Wallet,
  Zap,
} from "lucide-react";

/**
 * Registry of the icons addressable by name. Data files store `IconName`
 * strings and components render them through the shared `<Icon />`, so both
 * detail pages of `/explore-universities` resolve icons the same way.
 */
export const iconMap = {
  AlertCircle,
  Award,
  BarChart3,
  Bookmark,
  Bot,
  BookOpen,
  BrainCircuit,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  Code2,
  Cpu,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  FileText,
  Flag,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  HelpCircle,
  Hourglass,
  Info,
  Link2,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Percent,
  Phone,
  Search,
  Send,
  Server,
  Share2,
  ShieldCheck,
  Star,
  TrendingUp,
  Users,
  Wallet,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function getIcon(name: IconName): LucideIcon {
  return iconMap[name];
}
